$origin >
　　暑
　　中
　　お
　　見
　申舞
　しい
　上
　げ
　ま
　す
　。
< origin

$kyoto >
　　暑
　　中
　　お
　　見
　申舞
　しい
　上
　げ
　ま
　す
　え
　。
< kyoto

$osaka >
　　暑
　　中
　　お
　　見
　申舞
　しい
　上
　げ
　ま
　ん
　ね
　ん
　。
< osaka

$okinawa >
　ち
　ゅ
　｜
　う
　が
　な
　び
　ら
　。
< okinawa

$hiroshima >
　暑元
　い気
　のに
　うし
　。と
　　る
　　か
　　い
　　？
< hiroshima

$en >
  Summer greetings to you.

  or

  Have a nice summer.
< en

$ch >
  夏天的问候给你。

  要么

  祝你夏天愉快。
< ch
