$origin >
　　寒
　　中
　　お
　　見
　申舞
　しい
　上
　げ
　ま
　す
　。
< origin

$kyoto >
　　寒
　　中
　　お
　　見
　申舞
　しい
　上
　げ
　ま
　す
　え
　。
< kyoto

$osaka >
　　寒
　　中
　　お
　　見
　申舞
　しい
　上
　げ
　ま
　ん
　ね
　ん
　。
< osaka

$okinawa >
　ち
　ゅ
　｜
　う
　が
　な
　び
　ら
　。
< okinawa

$hiroshima >
　寒元
　い気
　のに
　う し
　。と
　　る
　　か
　　い
　　？
< hiroshima

$en >
  Winter greetings to you.

  or

  Have a nice winter.
< en

$ch >
  冬天的问候给你。

  要么

  过得很愉快。
< ch
